name: Publish new RSS feed

on: 
  - push:
      branches:
        - gh-pages
  - schedule:
      cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['2.2.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run
      run: dotnet run
    - name: Copy the output
      run: mv rss.xml ./website/rss.xml
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push the changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

# # Workflow:
# 1) Checkout code
# 2) Zbuduj apkę
# 3) Wygeneruj
# 4) Skopiuj do właściwego miejsca
# 5) Pushnij